---
# This playbook contains plays to grab RE frameworks/packages

- name: Creating RE directory in {{ re_dir }}
  file:
    path: "{{ re_dir }}"
    state: directory
    owner: "{{ user_dir }}"
    mode: '0755'
  become: yes

- name: Downloading RE Frameworks (IDA & Ghidra)
  get_url:
    url: "{{ item }}"
    dest: "{{ re_dir }}"
    mode: 755
    owner: "{{ user_dir }}"
  loop:
    - https://out7.hex-rays.com/files/idafree70_linux.run
    - https://ghidra-sre.org/ghidra_9.2_PUBLIC_20201113.zip
    - https://github.com/radareorg/cutter/releases/download/v1.12.0/Cutter-v1.12.0-x64.Linux.AppImage
  become: yes

- name: Installing JDK 11+ for Ghidra
  package:
    name: openjdk-11-jdk-headless
    state: latest
  become: yes

- name: Running IDA Installer
  command: "{{ re_dir }}idafree70_linux.run"
  become: yes

- name: Removing Running IDA Installer
  file : 
    path: "{{ re_dir }}idafree70_linux.run"
    state: absent
  become: yes

- name: 
  debug:
    msg: "By default, pip uses the pip version for the Ansible Python interpreter. For example, pip3 on python 3, and pip2 or pip on python 2."

- name: Installing Python bindings for capstone/unicorn/keystone/ropper
  pip:
    name: "{{ item }}"
  loop:
    - capstone 
    - unicorn
    - keystone-engine
    - ropper
  become: yes

- name: Downloading GEF (GDB Enhanced Features) from GitHub
  get_url: 
    url: https://github.com/hugsy/gef/raw/master/scripts/gef.sh 
    dest: /tmp/gef.sh
  become: no

- name: Installing GEF from /tmp/gef.sh.
  script: 
    cmd: /tmp/gef.sh
  become: no
