---
- name: Creating Linux Pwn directory in "{{ pwn_lin_dir }}"
  file:
    path: "{{ pwn_lin_dir }}"
    state: directory
    owner: "{{ user_dir }}"
    mode: '0755'
  become: yes

- name: Cloning Linux Focused tools 
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_lin_dir }}{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/rebootuser/LinEnum
    - https://github.com/OJ/gobuster
    - https://github.com/huntergregal/mimipenguin
    - https://github.com/gaffe23/linux-inject
  become: yes

- name: Downloading precompiled Packages
  get_url:
    url: "{{ item }}"
    dest: "{{ pwn_lin_dir }}"
    mode: 644
    owner: "{{ user_dir }}"
  loop:
    - https://github.com/kgretzky/pwndrop/releases/download/1.0.1/pwndrop-linux-amd64.tar.gz
  become: yes
