---
- name: Creating Linux Pwn directory in "{{ pwn_lin_dir }}"
  file:
    path: "{{ pwn_lin_dir }}"
    state: directory
    owner: "{{ user_dir }}"
    mode: '0755'
  become: yes

- name: Cloning Linux Focused tools 
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_lin_dir }}{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/rebootuser/LinEnum
    - https://github.com/OJ/gobuster
    - https://github.com/huntergregal/mimipenguin
    - https://github.com/gaffe23/linux-inject
    - https://github.com/gianlucaborello/libprocesshider
    - https://github.com/tls-attacker/TLS-Attacker
  become: yes

- name: Cloning Linux Focused tools  - rootkits
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_lin_dir }}/rootkits/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/f0rb1dd3n/Reptile
    - https://github.com/mempodippy/vlany
    - https://github.com/chokepoint/azazel
    - https://github.com/chokepoint/Jynx2
    - https://github.com/chokepoint/jynxkit
    - https://github.com/ChristianPapathanasiou/apache-rootkit
    - https://github.com/mncoppola/suterusu
    - https://github.com/jermeyyy/rooty
    - https://github.com/m0nad/Diamorphine
  become: yes

- name: Downloading precompiled Packages
  get_url:
    url: "{{ item }}"
    dest: "{{ pwn_lin_dir }}"
    mode: 644
    owner: "{{ user_dir }}"
  loop:
    - https://github.com/kgretzky/pwndrop/releases/download/1.0.1/pwndrop-linux-amd64.tar.gz
  become: yes
